/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-15 18:24:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminHeader.jsp", out, false);
      out.write("\r\n");
      out.write("   </div> \r\n");
      out.write("   \r\n");
      out.write("    <div id=\"homeimgDiv\"   >\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          <table class=\"scroll\"  >\r\n");
      out.write("  <tr class=\"tblhead\" >\r\n");
      out.write("    <th>Flight No.</th>\r\n");
      out.write("    <th>Flight Name</th>\r\n");
      out.write("    <th>From City</th>\r\n");
      out.write("    <th>To City</th>\r\n");
      out.write("    <th>Date</th>\r\n");
      out.write("    <th>Time</th>\r\n");
      out.write("    <th>Airport Name</th>\r\n");
      out.write("    <th>Ticket Price</th>\r\n");
      out.write("    <th>Description</th>\r\n");
      out.write("    <th>Edit</th>\r\n");
      out.write("    <th>Delete</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("   \r\n");
      out.write("    <tbody>\r\n");
      out.write("        <c:forEach items=\"${completelstflightData}\" var=\"fss\">\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("         <tr>\r\n");
      out.write("        \t   \r\n");
      out.write("        \t    <td><c:out value=\"${fss.flightno}\" /></td>\r\n");
      out.write("        \t    <td><c:out value=\"${fss.flightname}\"/></td>\r\n");
      out.write("        \t    <td><c:out value=\"${fss.fromcity}\"/></td>\r\n");
      out.write("        \t    <td><c:out value=\"${fss.tocity}\"/></td>\r\n");
      out.write("        \t    <td><c:out value=\"${fss.date}\"/></td>\r\n");
      out.write("        \t    <td><c:out value=\"${fss.time}\"/></td>\r\n");
      out.write("        \t    <td><c:out value=\"${fss.airportname}\"/></td>\r\n");
      out.write("        \t    <td><c:out value=\"${fss.ticketprice}\"/></td>\r\n");
      out.write("        \t    <td><c:out value=\"${fss.description}\"/></td>\r\n");
      out.write("        \t   \r\n");
      out.write(" \r\n");
      out.write("        \t     \r\n");
      out.write("\r\n");
      out.write("        \t    <td><a href=\"Edit?flightno=<c:out value='${fss.flightno}' />\">Edit</a>\r\n");
      out.write("        \t    <td><a href=\"delete?flightno=<c:out value='${fss.flightno}' />\">Delete</a>\r\n");
      out.write("        \t  </tr>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("        </c:forEach>\r\n");
      out.write("        </tbody>\r\n");
      out.write("       \r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("           \r\n");
      out.write("<!--            <img id=\"homeimgDiv\" alt=\"homeimg\" src=\"https://www.bhavyabharath.com/wp-content/uploads/2020/04/unnamed.jpg\"> -->\r\n");
      out.write("           </div>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
