/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-17 19:21:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.flightDataModel;
import java.util.ArrayList;
import java.util.List;

public final class editFlightData_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/MANIKANTA%20PC/Desktop/MJAVA/FlyAway%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FlyAway/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1609565690093L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.flightDataModel");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>FlyAway</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminHeader.jsp", out, false);
      out.write("\r\n");
      out.write("   </div> \r\n");
      out.write("  <br><br><br><br>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     <div id=\"addFlightDiv\">\r\n");
      out.write("    \r\n");
      out.write("     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function addFlightvalidateForm() {\r\n");
      out.write("\t  var flightno = document.forms[\"addFlightform\"][\"flightno\"].value;\r\n");
      out.write("\t  var flightname = document.forms[\"addFlightform\"][\"flightname\"].value;\r\n");
      out.write("\t  var fromcity = document.forms[\"addFlightform\"][\"fromcity\"].value;\r\n");
      out.write("\t  var tocity = document.forms[\"addFlightform\"][\"tocity\"].value;\r\n");
      out.write("\t  var date = document.forms[\"addFlightform\"][\"date\"].value;\r\n");
      out.write("\t  var time = document.forms[\"addFlightform\"][\"time\"].value;\r\n");
      out.write("\t  var airportname = document.forms[\"addFlightform\"][\"airportname\"].value;\r\n");
      out.write("\t  var ticketprice = document.forms[\"addFlightform\"][\"ticketprice\"].value;\r\n");
      out.write("\t  var description = document.forms[\"addFlightform\"][\"description\"].value;\r\n");
      out.write("\t   \r\n");
      out.write("\t  if (flightno == \"\") {\r\n");
      out.write("\t    alert(\"flightno must be filled out\");\r\n");
      out.write("\t    return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if (flightname == \"\") {\r\n");
      out.write("\t\t    alert(\"flightname must be filled out\");\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  if (fromcity == \"\") {\r\n");
      out.write("\t\t    alert(\"fromcity must be filled out\");\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  if (tocity == \"\") {\r\n");
      out.write("\t\t    alert(\"tocity must be filled out\");\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t  if (date == \"\") {\r\n");
      out.write("\t\t\t    alert(\"date must be filled out\");\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t  if (time == \"\") {\r\n");
      out.write("\t\t\t    alert(\"time must be filled out\");\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t  if (airportname == \"\") {\r\n");
      out.write("\t\t\t    alert(\"airportname must be filled out\");\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  if (ticketprice == \"\") {\r\n");
      out.write("\t\t\t\t    alert(\"ticketprice must be filled out\");\r\n");
      out.write("\t\t\t\t    return false;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t  if (description == \"\") {\r\n");
      out.write("\t\t\t\t    alert(\"description must be filled out\");\r\n");
      out.write("\t\t\t\t    return false;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".textboxstyle {\r\n");
      out.write("  border-radius:5px;\r\n");
      out.write("   height: 30px;\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".buttonstyle\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("background-color: Cyan;\r\n");
      out.write("color: white;\r\n");
      out.write("padding:20px;\r\n");
      out.write("margin: 5px;\r\n");
      out.write(" font-size: large;\r\n");
      out.write(" font-weight: bold;\r\n");
      out.write("border-radius: 12px;\r\n");
      out.write(" \r\n");
      out.write(" cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(".buttonstyle:hover {\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  color: #f00;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  width: 134px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-variant: small-caps;\r\n");
      out.write("  background: White;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /editFlightData.jsp(29,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/editFlightData.jsp(29,5) '${completelstflightData}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${completelstflightData}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /editFlightData.jsp(29,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("fss");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      <form name=\"addFlightform\" class=\"addflightformstyle\" action=\"UpdateFlightDataServlet\"   onsubmit=\"return addFlightvalidateForm()\">\r\n");
            out.write("       Flight No : <input  class=\"textboxstyle\" type=\"text\" name=\"flightno\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.flightno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" readonly ><br><br>\r\n");
            out.write("      Flight Name : <input  class=\"textboxstyle\" type=\"text\" name=\"flightname\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.flightname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><br><br>\r\n");
            out.write("      From City : <input  class=\"textboxstyle\" type=\"text\" name=\"fromcity\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.fromcity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" ><br><br>\r\n");
            out.write("      To City : <input class=\"textboxstyle\" type=\"text\" name=\"tocity\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.tocity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><br><br>\r\n");
            out.write("      Date : <input class=\"textboxstyle\" type=\"text\" name=\"date\"  value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><br><br>\r\n");
            out.write("      Time : <input class=\"textboxstyle\" type=\"text\" name=\"time\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><br><br>\r\n");
            out.write("      Airport Name : <input class=\"textboxstyle\" type=\"text\" name=\"airportname\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.airportname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><br><br>\r\n");
            out.write("      Ticket Price : <input class=\"textboxstyle\" type=\"text\" name=\"ticketprice\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.ticketprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><br><br>\r\n");
            out.write("      Description : <input class=\"textboxstyle\" type=\"text\" name=\"description\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fss.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><br><br>\r\n");
            out.write("      <input type=\"submit\" class=\"buttonstyle\"  value=\"Update Flight Data\">\r\n");
            out.write("      </form>\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
